apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myfirst-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/CELESTINSAMPLE/mynginxrepo.git
    targetRevision: HEAD
    path: myfirstapp
  destination: 
    server: https://kubernetes.default.svc
    namespace: firstnamespace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
